#define mensajeKilometros "Ingresar kilometros recorridos"
#define mensajeErrorInicial "Error en el ingreso de datos"
#define mensajeCombustible "Ingresar precio del combustible (por litro)"
#define mensajeMonto "Ingresar monto total de la compra"
#define mensajeErrorMedio "Error en el ingreso de datos, se muestran los resultados obtenidos hasta ahora"
#define mensajeResultados "*RESULTADOS*"
#define mensajeFinalRendProm "Rendimiento promedio: "
#define mensajeFinalMejorRend "Mejor rendimiento: "
#define mensajeFinalPeorRend "Peor rendimiento: "
#define mensajeFinalDistancia "Distancia total recorrida: "
#define mensajeFinalCombustible "Combustible total consumido: "
#define mensajeFinalCosto "Costo total de su vehiculo: $"
#define unidadLitro100km " l/100km"
#define unidadKm " km"
#define unidadLitros " litros"
#define mensajeFinal "Gracias, vuelva pronto!"

