#define mensajeInicial "Inserte numero de dia (entre 1 y 366)"
#define mensajeError "Error en el ingreso de datos"
#define mensajeDomingo "El dia ingresado cae el domingo"
#define mensajeLunes "El dia ingresado cae el lunes"
#define mensajeMartes "El dia ingresado cae el martes"
#define mensajeMiercoles "El dia ingresado cae el miercoles"
#define mensajeJueves "El dia ingresado cae el jueves"
#define mensajeViernes "El dia ingresado cae el viernes"
#define mensajeSabado "El dia ingresado cae el sabado"
#define mensajeFinal "Gracias, vuelva pronto!"

